title: MedCore
description: Medical equipment solutions
url: "https://gheorghe2973.github.io"
baseurl: "/tum-web-lab2"

# Build settings
markdown: kramdown
highlighter: rouge

# Collections
collections:
  products:
    output: false

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - "*.sh"
